# Generated by Django 4.0.3 on 2022-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(db_index=True, verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Должность'),
        ),
    ]
